TRUNCATE owners CASCADE;

insert into owners (firstName, lastName, address) values ('Ruthe', 'McGow', '955 Arrowood Junction');
insert into owners (firstName, lastName, address) values ('Luci', 'Gregoli', '9 Arkansas Crossing');
insert into owners (firstName, lastName, address) values ('Polly', 'Hawkswell', '8421 Oak Valley Park');
insert into owners (firstName, lastName, address) values ('Gabbie', 'Allbones', '73 Quincy Terrace');
insert into owners (firstName, lastName, address) values ('Chick', 'Cornil', '687 Ronald Regan Terrace');
insert into owners (firstName, lastName, address) values ('Lorie', 'Bougen', '8 Nancy Lane');
insert into owners (firstName, lastName, address) values ('Ewell', 'Esel', '7 Graceland Center');
insert into owners (firstName, lastName, address) values ('Ernesta', 'Zimmermanns', '913 Bowman Plaza');
insert into owners (firstName, lastName, address) values ('Page', 'Flecknoe', '76029 Boyd Parkway');
insert into owners (firstName, lastName, address) values ('Salem', 'Lyndon', '8 Arkansas Street');
insert into owners (firstName, lastName, address) values ('Celisse', 'Ales0', '68606 Oneill Circle');
insert into owners (firstName, lastName, address) values ('Lindi', 'Halbert', '00018 Banding Court');
insert into owners (firstName, lastName, address) values ('Vikki', 'Prewett', '533 Lighthouse Bay Parkway');
insert into owners (firstName, lastName, address) values ('Rory', 'Schurig', '5 Messerschmidt Street');
insert into owners (firstName, lastName, address) values ('Danny', 'Sirman', '03000 Sage Drive');

TRUNCATE dogs CASCADE;

insert into dogs (name, gender, ownerId) values ('Myrtle', 'Female', 14);
insert into dogs (name, gender, ownerId) values ('Kate', 'Female', 8);
insert into dogs (name, gender, ownerId) values ('Josiah', 'Male', 7);
insert into dogs (name, gender, ownerId) values ('Chance', 'Male', 10);
insert into dogs (name, gender, ownerId) values ('Hi', 'Male', 15);
insert into dogs (name, gender, ownerId) values ('Rayner', 'Male', 4);
insert into dogs (name, gender, ownerId) values ('Austin', 'Male', 6);
insert into dogs (name, gender, ownerId) values ('Lorrayne', 'Female', 13);
insert into dogs (name, gender, ownerId) values ('Harald', 'Male', 4);
insert into dogs (name, gender, ownerId) values ('Flory', 'Male', 11);
insert into dogs (name, gender, ownerId) values ('Queenie', 'Female', 13);
insert into dogs (name, gender, ownerId) values ('Herculie', 'Male', 1);
insert into dogs (name, gender, ownerId) values ('Salvatore', 'Male', 6);
insert into dogs (name, gender, ownerId) values ('Jamal', 'Male', 10);
insert into dogs (name, gender, ownerId) values ('Trula', 'Female', 7);
insert into dogs (name, gender, ownerId) values ('Jyoti', 'Female', 1);
insert into dogs (name, gender, ownerId) values ('Francisco', 'Male', 6);
insert into dogs (name, gender, ownerId) values ('Trefor', 'Male', 14);
insert into dogs (name, gender, ownerId) values ('Amy', 'Female', 1);
insert into dogs (name, gender, ownerId) values ('Ingram', 'Male', 12);
insert into dogs (name, gender, ownerId) values ('George', 'Female', 10);
insert into dogs (name, gender, ownerId) values ('Helenelizabeth', 'Female', 15);
insert into dogs (name, gender, ownerId) values ('Robinette', 'Female', 7);
insert into dogs (name, gender, ownerId) values ('Rice', 'Male', 2);
insert into dogs (name, gender, ownerId) values ('Ulrick', 'Male', 7);
insert into dogs (name, gender, ownerId) values ('Rivalee', 'Female', 11);
insert into dogs (name, gender, ownerId) values ('Vanni', 'Female', 1);
insert into dogs (name, gender, ownerId) values ('Aurore', 'Female', 2);
insert into dogs (name, gender, ownerId) values ('Wynnie', 'Female', 14);
insert into dogs (name, gender, ownerId) values ('Henri', 'Male', 4);
insert into dogs (name, gender, ownerId) values ('Carlotta', 'Female', 2);
insert into dogs (name, gender, ownerId) values ('Anissa', 'Female', 2);
insert into dogs (name, gender, ownerId) values ('Cristine', 'Female', 4);
insert into dogs (name, gender, ownerId) values ('Burton', 'Male', 2);
insert into dogs (name, gender, ownerId) values ('Evey', 'Female', 13);
insert into dogs (name, gender, ownerId) values ('Maxim', 'Male', 2);
insert into dogs (name, gender, ownerId) values ('Corinna', 'Female', 2);
insert into dogs (name, gender, ownerId) values ('Prissie', 'Female', 3);
insert into dogs (name, gender, ownerId) values ('Friederike', 'Female', 8);
insert into dogs (name, gender, ownerId) values ('Herman', 'Male', 5);
insert into dogs (name, gender, ownerId) values ('Lynnell', 'Female', 9);
insert into dogs (name, gender, ownerId) values ('Ladonna', 'Female', 4);
insert into dogs (name, gender, ownerId) values ('Kaitlynn', 'Female', 2);
insert into dogs (name, gender, ownerId) values ('Neile', 'Female', 10);
insert into dogs (name, gender, ownerId) values ('Gian', 'Male', 1);